services:
    python-app:
        build:
            context: .
        environment:
            SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@postgres:5432/impact_calculator"
        ports:
            - 5000:5000
        depends_on:
            db:
                condition: service_healthy
        networks:
            postgres:
    
    db:
        image: postgres:14.8-alpine3.18
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "impact_calculator"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        expose:
            - 5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
            
        networks:
            postgres:

volumes:
    db-data:
        
networks:
    postgres:
        driver: bridge
